Update travisci

diff --git a/travisci b/travisci
--- a/travisci
+++ b/travisci
@@ -54,6 +54,14 @@ else
     eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)"
 fi
 
+echo "💼 Building Release";
+swift build -c release
+if [[ $? != 0 ]]; 
+then 
+    echo "❌  Build for release failed";
+    exit 1; 
+fi
+
 echo "📅 Version: `swift --version`";
 echo "🚀 Building";
 swift build
@@ -63,24 +71,27 @@ then
     exit 1; 
 fi
 
-echo "💼 Building Release";
-swift build -c release
-if [[ $? != 0 ]]; 
-then 
-    echo "❌  Build for release failed";
-    exit 1; 
-fi
-
 echo "Get Data"
 wget https://raw.githubusercontent.com/OpenKitten/Mongo-Assets/master/zips.json
 
 echo "Prepare Data"
 mongoimport --host localhost --port 27017 --db=mongokitten-unittest --collection=zips --drop zips.json 
-mongoimport --host localhost --port 27018 --db=mongokitten-unittest --collection=zips --drop zips.json 
+
+if [[ $OS == "macos" ]];
+then
+    mongoimport --host localhost --port 27018 --db=mongokitten-unittest --collection=zips --drop zips.json 
+fi
 
 echo "🔎 Testing";
 
 swift test
+if [[ $? != 0 ]]; 
+then 
+    echo "❌ Tests failed";
+    exit 1; 
+fi
+export mongokittentest="mongodb://localhost:27018/mongokitten-unittest?appname=xctest"
+/opt/swift/swift-3.0/usr/bin/swift test
 if [[ $? != 0 ]]; 
 then 
     echo "❌ Tests failed";
